#!/bin/bash

conda init bash
conda deactivate
conda remove -n micro --all --yes
conda env create -f latest.yml -n micro
conda activate micro
conda env export --no-builds | grep -v "prefix" > environment.yml
